import type { Metadata } from "next";
import Header from "@/components/shared/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayoutWithHeader({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex items-center flex-col">
      <div className="min-h-screen max-w-screen-xl">
        <Header />
        <div className="p-4">{children}</div>
      </div>
    </div>
  );
}
