import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../../components/shared/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="dark:bg-gray-950 min-h-screen">
      <Header />
      {children}
    </div>
  );
}
