"use client";
import { useRouter } from "next/navigation";
// import type { Metadata } from "next";
import Header from "../../components/shared/dashboard/header";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const DashboardLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const router = useRouter();

  const handleSignOut = () => {
    localStorage.removeItem("accessToken");
    localStorage.removeItem("refreshToken");
    router.push("/");
  };
  return (
    <div className="dark:bg-gray-950 min-h-screen">
      <Header onSingOut={handleSignOut} />
      {children}
    </div>
  );
};

export default DashboardLayout;
