import type { Metadata } from "next";
import Header from "../../components/shared/header";
import Footer from "@/components/shared/footer";
import CustomNavbar from "@/components/shared/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="dark:bg-gray-950 min-h-screen">
      <CustomNavbar />
      {children}
      <Footer />
    </div>
  );
}
